config/routes.rb
Budget::Application.routes.draw do

  get 'contact_us', to: 'messages#new', as: 'contact_us'
  get 'about', to: 'static#about', as: 'about'
  get 'legal', to: 'static#legal', as: 'legal'

  get 'monthly_expenses', to: 'expenses#monthly_expenses', as: 'monthly_expenses'
  get 'regular_spending', to: 'expenses#index', as: 'regular_spending'

  get 'current_month', to: 'static#current_month', as: 'current_month'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get "account_information" => "users#edit", :as => :account_information

  resources :users do
    resources :expenses
    resources :incomes
    resources :savings
  end
  
  resources :expenses
  resources :incomes
  resources :sessions
  resources :savings
  resources :password_resets
  resources :messages

  root 'static#index'

  

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :expenses, :dependent => :destroy
  has_many :incomes, :dependent => :destroy
  has_many :savings, :dependent => :destroy

  before_create { generate_token(:auth_token) }
  before_create :set_original_supporter
  
  validates_uniqueness_of :email
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates_inclusion_of :time_zone, in: ActiveSupport::TimeZone.zones_map(&:name)

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end

  def set_original_supporter
    self.original_supporter = true
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  def full_name
    first_name.blank? && last_name.blank? ? email : first_name + " " + last_name
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter do
    params[:user] &&= user_params
  end
  load_and_authorize_resource

  def new
    if current_user
      redirect_to current_month_path, :flash => { :alert => "You are already logged into an account." }
    else
      @user = User.new
    end
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      cookies[:auth_token] = @user.auth_token
      UserMailer.new_user_signup(@user).deliver
      UserMailer.new_user_notify_admin(@user).deliver
      redirect_to current_month_path, notice: "Welcome to rainybudget!"
    else
      render "new"
    end
  end

  def edit
    @user = User.find(current_user)
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to current_month_path, :notice => "Successfully updated account information."
    else
      redirect_to current_month_path, :flash => { :alert => "There was an error updating your user information." }
    end
  end

  private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name, :time_zone)
    end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="row">
  <div class="large-12 columns date-row">
    <div class="row">
      <div class="large-4 columns">
        <h3><%= Time.zone.now.strftime("%A") %> <small><%= Time.zone.now.strftime("%b %d, %Y") %></small></h3>
      </div>
      <div class="large-8 columns">
        <h3 class="right"><%= how_much_money_is_left %></h3>
      </div>
    </div>
    <hr />
  </div>
</div>

<div class="row">
  <div class="large-3 columns">
    <ul class="side-nav">
      <li><%= link_to "<i class='foundicon-graph'></i>&nbsp; #{this_month} Overview".html_safe, current_month_path %></li>
      <li><%= link_to "<i class='foundicon-checkmark success-icon'></i>&nbsp; Savings".html_safe, savings_path %></li>
      <li><%= link_to "<i class='foundicon-page alert-icon'></i>&nbsp; Regular Spending".html_safe, regular_spending_path %></li>
      <li><%= link_to "<i class='foundicon-page primary-icon'></i>&nbsp; Monthly Expenses".html_safe, monthly_expenses_path %></li>
      <li><%= link_to "<i class='foundicon-page secondary-icon'></i>&nbsp; Income".html_safe, incomes_path %></li>
      <li class="divider"></li>
      <li class="active"><%= link_to "Account Information", account_information_path %></li>
    </ul>
  </div>


  <div class="large-9 columns">
    <div class="row">
      <div class="large-12 columns">
        <h4>Account Information</h4>
        <hr />
      </div>
      <div class="row">
        <div class="large-6 columns">
          <div class="large-12 columns">
            <%= form_for @user do |f| %>
              <%= f.label :first_name, "First Name" %>
              <%= f.text_field :first_name %><br />

              <%= f.label :last_name, "Last Name" %>
              <%= f.text_field :last_name %><br />

              <%= f.label :time_zone, "Select Time Zone" %>
              <%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones %><br />

              <p class="user-account-info" style="padding-top: 30px;">
                Join Date: <%= current_user.created_at.strftime("%B %d, %Y") %>
                <br />
                <% if current_user.original_supporter? %> 
                  Account Status: Original Supporter
                <% else %>
                  Account Status: Regular Member
                <% end %>
              </p>
              <br />
              <%= f.submit "Save Account Information", :class => "button right" %>
            <% end %>
          </div>
        </div>
        <div class="large-6 columns">
          <p>
            We appreciate your support and hope you find this software useful. Feel free to <%= link_to "contact us", contact_us_path %> if you have any suggestions, questions, concerns, or would simply like to say hi.
          </p>
          <p>
            Thank you!
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="large-5 columns">
    <br />
    <h2>Welcome!</h2>
    <p>
      Creating an account is free, and right now during the beta, a new account means lifetime original supporter status! This gives you priority over other users and special privledges later in the life of rainybudget.com.
    </p>
    <h4>How does rainybudget.com work?</h4>
    <ol style="padding: 0px 0px 0px 30px;">
      <li>Enter expenses to track spending.</li>
      <li>Record your income for the current month.</li>
      <li>Pick an amount you want to set aside for savings.</li>
    </ol>
    <p>
      And that's it. Each month you'll be able to see exactly how much you have left to spend, and as long as you don't go over, you'll be saving money!
    </p>
    <p>
      Thank you! We hope you enjoy using rainybudget.com.
    </p>
  </div>

  <div class="large-7 columns">
    <fieldset style="padding-top: 20px;">
      <h4>Get started today! <small>Escape the month-to-month</small></h4>
      <hr />
      <%= form_for @user do |f| %>
        <% if @user.errors.any? %>
          <div class="small-12 columns">
            <label class="error">Your account could not be created!<br /><br /> Please make sure you're using a valid email address and your passwords match.</label>
            <hr />
          </div>
        <% end %>

        <div class="small-12 columns">
          <div class="small-4 columns">
            <%= f.label :email, "Email Address", :class => "right inline" %>
          </div>
          <div class="small-8 columns">
            <%= f.text_field :email, :placeholder => "katie.bell@gmail.com" %>
          </div>
        </div>

        <div class="small-12 columns">
          <div class="small-4 columns">
            <%= f.label :password, "Password", :class => "right inline" %>
          </div>
          <div class="small-8 columns">
            <%= f.password_field :password %>
          </div>
        </div>

        <div class="small-12 columns">
          <div class="small-4 columns">
            <%= f.label :password_confirmation, "Confirm Password", :class => "right inline" %>
          </div>
          <div class="small-8 columns">
            <%= f.password_field :password_confirmation %>
          </div>
        </div>

        <div class="small-12 columns">
          <div class="small-4 columns">
            <%= f.label :time_zone, "Select Time Zone", :class => "right inline" %>
          </div>
          <div class="small-8 columns">
            <%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones %>
          </div>
        </div>

        <div class="small-12 columns">
          <div class="small-12 columns">
            <br />
            <%= f.submit "Create my new account", data: { disable_with: 'Creating your account...' }, :class => "button right" %>
          </div>
        </div>
      <% end %>
      <div class="create-account-info-box">
        <p>
          By creating an account you agree to the <%= link_to "rainybudget.com terms of use", legal_path %> - rainybudget.com is not a replacement for any professional, legal, or accounting services. Information provided by the rainybudget.com services are directly affected by variable input and are not guaranteed to be accurate.
        </p>
      </div>
    </fieldset>
  </div>
</div>