config/routes.rb
Budget::Application.routes.draw do

  get 'contact_us', to: 'messages#new', as: 'contact_us'
  get 'about', to: 'static#about', as: 'about'
  get 'legal', to: 'static#legal', as: 'legal'

  get 'monthly_expenses', to: 'expenses#monthly_expenses', as: 'monthly_expenses'
  get 'regular_spending', to: 'expenses#index', as: 'regular_spending'

  get 'current_month', to: 'static#current_month', as: 'current_month'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get "account_information" => "users#edit", :as => :account_information

  resources :users do
    resources :expenses
    resources :incomes
    resources :savings
  end
  
  resources :expenses
  resources :incomes
  resources :sessions
  resources :savings
  resources :password_resets
  resources :messages

  root 'static#index'

  

end

app/views/shared/_flash_notify.html.erb
<div class="row">
  <div class="large-12 columns" style="height: 37px;">
    <% if flash[:error] %>
      <div class="alert-box alert text-center"><%= flash[:error] %></div>
    <% end %>

    <%if flash[:notice] %>
      <div class="alert-box text-center"><%= flash[:notice] %></div>
    <% end %>

    <%if flash[:alert] %>
      <div class="alert-box alert text-center"><%= flash[:alert] %></div>
    <% end %>
  </div>
</div>

app/views/shared/_regular_footer.html.erb
<footer class="row">
  <div class="large-12 columns">
    <hr />
    <div class="row">
      <div class="large-3 columns">
        <p class="footer-company">&copy; <%= Time.zone.now.year %> Halimede LLC</p>
      </div>
      <div class="large-9 columns">
        <ul class="inline-list right footer-links">
          <li><%= link_to "Legal Information", legal_path %></li>
          <li><%= link_to "About rainybudget.com", about_path %></li>
          <li><%= link_to "Contact Us", contact_us_path %></li>
          <% if current_user %>
            <li><%= link_to "Log Out", logout_path %></li>
          <% else %>
            <li><%= link_to "Login Page", login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_regular_nav.html.erb
<div class="header-span header-links">
  

  <div class="row">
    <div class="large-4 columns">
      <div class="header-logo">
        <% if current_user %>
          <%= link_to(image_tag("rainybudgetlogo.png", :style => "margin: 10px 0px 10px 0px"), current_month_path) %>
        <% else %>
          <%= link_to(image_tag("rainybudgetlogo.png", :style => "margin: 10px 0px 10px 0px"), root_url) %>
        <% end %>
      </div>
    </div>

    <div class="large-8 columns main-nav">
      <ul class="right">
        <% if !current_user %>
          <li class="right">
            <a href="#" data-dropdown="drop1">Access my Account</a>
            <div id="drop1" class="f-dropdown content small" data-dropdown-form>
              <%= form_tag sessions_path do %>
                <p>
                  <%= label_tag :email, "Email Address" %>
                  <%= text_field_tag :email, params[:email], :placeholder => "katie.bell@gmail.com" %>
                </p>
                <p>
                  <%= label_tag :password, "Password" %>
                  <%= password_field_tag :password %>
                </p>
                <p>
                  <%= check_box_tag :remember_me, 1, params[:remember_me], :style => "display:inline !important" %>
                  <%= label_tag :remember_me, "Remember Me", :style => "display:inline !important" %>
                  <br />
                  <span class="forgot-remember"><%= link_to "Password Recovery", new_password_reset_path %></span>
                </p>
                <%= submit_tag "Sign In".html_safe, data: { disable_with: 'Logging in...' }, :class => "button right" %>
              <% end %>
            </div>
          </li>
          <li class="right"><%= link_to "Create an Account", signup_path %></li>
          <li class="right"><%= link_to "Contact Us", contact_us_path %>
          <li class="right"><%= link_to "About rainybudget.com", about_path %>
        <% end %>
        <% if current_user %>
          <li class="right"><%= link_to "View my Budget", current_month_path %></li>
          
          <li class="right">Logged in as <%= current_user.full_name %></li>
        <% end %>
        
      </ul>
    </div>
  </div>

</div>